"""
Rocket League event extractor.

Supports two input formats:

1. Ballchasing API JSON (primary, no external dependency):
   GET /replays/{id} returns per-player aggregate stats (shots, goals, saves,
   assists, demos, boost counts). A synthetic event stream is generated by
   distributing events proportionally across the game duration, with goal
   events anchoring play boundaries.

2. carball / rrrocket parsed binary (legacy, higher fidelity):
   Preserves exact hit-by-hit and boost event timestamps from the .replay file.
   Requires carball or rrrocket to be installed.

Per Q7 sign-off (D-22): boost-enriched extraction — resource_gain, resource_spend,
and resource_budget events are included alongside ball-contact events.
"""

from __future__ import annotations

import hashlib
import logging
from typing import Any

from ...common.schema import EventStream, GameEvent

logger = logging.getLogger(__name__)

# carball hit type → normalized event type
CARBALL_HIT_TYPE_MAP = {
    "shot": "engage_decision",
    "save": "disengage_decision",
    "goal": "objective_capture",
    "assist": "team_coordinate",
    "epic_save": "disengage_decision",
    "hit": "objective_contest",
    "pass": "team_coordinate",
    "dribble": "position_commit",
    "aerial": "timing_commit",
    "clear": "disengage_decision",
    "demo": "risk_accept",
}

BOOST_EVENT_MAP = {
    "pickup_big": "resource_gain",
    "pickup_small": "resource_gain",
    "use": "resource_spend",
    "depleted": "resource_spend",
    "low_boost": "resource_budget",
}

LOW_BOOST_THRESHOLD = 25  # boost amount below which player is "low boost"


class RocketLeagueExtractor:

    def extract(self, record: dict[str, Any]) -> EventStream:
        game_id = self._get_game_id(record)
        stream = EventStream(game_id=game_id, cell="rocket_league")

        if _is_ballchasing_json(record):
            self._extract_ballchasing_json(record, stream)
        elif "_hits" in record:
            self._extract_carball(record, stream)
        elif "network_frames" in record:
            self._extract_rrrocket(record, stream)
        else:
            logger.warning(f"Unknown replay format for {game_id}")

        stream.events.sort(key=lambda e: e.timestamp)
        for i, e in enumerate(stream.events):
            e.sequence_idx = i

        return stream

    # ------------------------------------------------------------------
    # Ballchasing API JSON extraction (primary path)
    # ------------------------------------------------------------------

    def _extract_ballchasing_json(self, record: dict, stream: EventStream) -> None:
        """
        Synthesize an event stream from Ballchasing aggregate stats.

        Goal events anchor play boundaries (used by RocketLeagueT to segment
        chains). Shot, save, demo, and boost events are distributed across
        the game timeline proportional to each player's aggregate counts.
        """
        duration = max(float(record.get("duration", 300)), 1.0)

        # Collect all players with team label
        all_players: list[tuple[str, dict]] = []
        for team_key in ("blue", "orange"):
            for p in record.get(team_key, {}).get("players", []):
                all_players.append((team_key, p))

        # Build goal timeline: each player's goal count → synthetic timestamps
        # Goals are distributed evenly across duration then sorted by team
        goal_entries: list[tuple[float, str, str]] = []  # (ts, actor_id, team)
        seq_goals: list[tuple[str, str]] = []
        for team_key, p in all_players:
            n_goals = int(p.get("stats", {}).get("core", {}).get("goals", 0))
            actor = _player_id(p)
            for _ in range(n_goals):
                seq_goals.append((actor, team_key))

        total_goals = len(seq_goals)
        if total_goals > 0:
            interval = duration / (total_goals + 1)
            for i, (actor, team_key) in enumerate(seq_goals):
                goal_entries.append((interval * (i + 1), actor, team_key))

        seq = 0
        for ts, actor, team_key in goal_entries:
            stream.append(GameEvent(
                timestamp=ts,
                event_type="objective_capture",
                actor=actor,
                location_context={
                    "synthetic": True, "source": "ballchasing_api",
                    "team_color": team_key,
                    "duration_s": duration,
                    "score_blue": int(record.get("blue", {}).get("stats", {}).get("core", {}).get("goals", 0)),
                    "score_orange": int(record.get("orange", {}).get("stats", {}).get("core", {}).get("goals", 0)),
                },
                raw_data_blob={},
                cell="rocket_league",
                game_id=stream.game_id,
                sequence_idx=seq,
                actor_team=team_key,
            ))
            seq += 1

        # Per-player non-goal events: shots, saves, demos, assists, boost pickups
        for team_key, p in all_players:
            actor = _player_id(p)
            core = p.get("stats", {}).get("core", {})
            boost = p.get("stats", {}).get("boost", {})

            # A6: include `action_label` so the model can distinguish shot
            # vs save vs assist vs demo vs boost-pickup beyond just the
            # abstract `event_type` bucket. Best-effort within BallChasing
            # aggregate-stat data ceiling.
            player_events: list[tuple[str, int, str]] = [
                ("engage_decision",    int(core.get("shots", 0)),                          "shot"),
                ("disengage_decision", int(core.get("saves", 0)),                          "save"),
                ("team_coordinate",    int(core.get("assists", 0)),                        "assist"),
                ("risk_accept",        int(core.get("demo", {}).get("inflicted", 0)),     "demo_inflicted"),
                ("resource_gain",      int(boost.get("count_collected_big", 0))
                                       + int(boost.get("count_collected_small", 0)),       "boost_pickup"),
            ]

            score_blue = int(record.get("blue", {}).get("stats", {}).get("core", {}).get("goals", 0))
            score_orange = int(record.get("orange", {}).get("stats", {}).get("core", {}).get("goals", 0))

            for event_type, count, action_label in player_events:
                if count == 0:
                    continue
                interval = duration / (count + 1)
                for j in range(count):
                    # Small per-player offset avoids all players having identical timestamps
                    ts = interval * (j + 1) + all_players.index((team_key, p)) * 0.05
                    stream.append(GameEvent(
                        timestamp=ts,
                        event_type=event_type,
                        actor=actor,
                        location_context={
                            "synthetic": True, "source": "ballchasing_api",
                            "team_color": team_key,
                            "duration_s": duration,
                            "score_blue": score_blue,
                            "score_orange": score_orange,
                            "action_label": action_label,
                        },
                        raw_data_blob={},
                        cell="rocket_league",
                        game_id=stream.game_id,
                        sequence_idx=seq,
                        actor_team=team_key,
                    ))
                    seq += 1

            # Boost spend: estimate from bcpm (boost consumption per minute)
            bcpm = float(boost.get("bcpm", 0))
            n_boost_spend = max(0, int(bcpm * (duration / 60.0) / 100.0))
            if n_boost_spend > 0:
                interval = duration / (n_boost_spend + 1)
                for j in range(n_boost_spend):
                    ts = interval * (j + 1) + all_players.index((team_key, p)) * 0.05
                    stream.append(GameEvent(
                        timestamp=ts,
                        event_type="resource_spend",
                        actor=actor,
                        location_context={"synthetic": True, "bcpm": bcpm},
                        raw_data_blob={},
                        cell="rocket_league",
                        game_id=stream.game_id,
                        sequence_idx=seq,
                        actor_team=team_key,
                    ))
                    seq += 1

    # ------------------------------------------------------------------
    # carball binary extraction (legacy / high-fidelity path)
    # ------------------------------------------------------------------

    def _extract_carball(self, record: dict, stream: EventStream) -> None:
        seq = 0
        for hit in record.get("_hits", []):
            ev = self._parse_carball_hit(hit, stream.game_id, seq)
            if ev:
                stream.append(ev)
                seq += 1

        for player in record.get("_players", []):
            for boost_ev in player.get("boost_events", []):
                ev = self._parse_boost_event(boost_ev, player, stream.game_id, seq)
                if ev:
                    stream.append(ev)
                    seq += 1

        for player in record.get("_players", []):
            boost_history = player.get("boost_history", [])
            prev_amount = None
            for frame, amount in boost_history:
                if prev_amount is not None:
                    if prev_amount >= LOW_BOOST_THRESHOLD and amount < LOW_BOOST_THRESHOLD:
                        stream.append(GameEvent(
                            timestamp=float(frame) / 30.0,
                            event_type="resource_budget",
                            actor=str(player.get("id", {}).get("id", "unknown")),
                            location_context={
                                "boost_amount": amount,
                                "threshold": LOW_BOOST_THRESHOLD,
                                "transition": "high_to_low",
                            },
                            raw_data_blob={"frame": frame, "amount": amount},
                            cell="rocket_league",
                            game_id=stream.game_id,
                            sequence_idx=seq,
                        ))
                        seq += 1
                prev_amount = amount

    def _extract_rrrocket(self, record: dict, stream: EventStream) -> None:
        props = record.get("properties", {})
        goals = props.get("Goals", {}).get("value", [])
        seq = 0
        for goal in goals:
            frame = goal.get("frame", 0)
            ts = frame / 30.0
            player_name = goal.get("PlayerName", {}).get("value", "unknown")
            stream.append(GameEvent(
                timestamp=ts,
                event_type="objective_capture",
                actor=player_name,
                location_context={"frame": frame, "goal_data": goal},
                raw_data_blob=goal,
                cell="rocket_league",
                game_id=stream.game_id,
                sequence_idx=seq,
            ))
            seq += 1

    # ------------------------------------------------------------------
    # carball helpers
    # ------------------------------------------------------------------

    def _parse_carball_hit(self, hit: dict, game_id: str, seq: int) -> GameEvent | None:
        try:
            ts = float(hit.get("frame_number", hit.get("frame", 0))) / 30.0
            actor_id = str(hit.get("player_id", {}).get("id", "unknown"))
            hit_type = hit.get("hit_type", "hit").lower()
            etype = CARBALL_HIT_TYPE_MAP.get(hit_type, "objective_contest")
            return GameEvent(
                timestamp=ts,
                event_type=etype,
                actor=actor_id,
                location_context={
                    "ball_x": hit.get("ball_data", {}).get("pos_x", 0),
                    "ball_y": hit.get("ball_data", {}).get("pos_y", 0),
                    "ball_z": hit.get("ball_data", {}).get("pos_z", 0),
                    "hit_type": hit_type,
                    "distance_to_goal": hit.get("distance_to_goal", 0),
                },
                raw_data_blob=hit,
                cell="rocket_league",
                game_id=game_id,
                sequence_idx=seq,
                actor_team=str(hit.get("team", "")),
            )
        except Exception as e:
            logger.debug(f"Carball hit parse error: {e}")
            return None

    def _parse_boost_event(
        self, boost_ev: dict, player: dict, game_id: str, seq: int
    ) -> GameEvent | None:
        try:
            boost_type = boost_ev.get("type", "pickup_big")
            etype = BOOST_EVENT_MAP.get(boost_type, "resource_gain")
            ts = float(boost_ev.get("frame", 0)) / 30.0
            return GameEvent(
                timestamp=ts,
                event_type=etype,
                actor=str(player.get("id", {}).get("id", "unknown")),
                location_context={
                    "boost_type": boost_type,
                    "boost_amount": boost_ev.get("amount", 0),
                },
                raw_data_blob=boost_ev,
                cell="rocket_league",
                game_id=game_id,
                sequence_idx=seq,
            )
        except Exception as e:
            logger.debug(f"Boost event parse error: {e}")
            return None

    @staticmethod
    def _get_game_id(record: dict) -> str:
        replay_id = (
            record.get("id")
            or record.get("properties", {}).get("Id", {}).get("value")
            or ""
        )
        if replay_id:
            return f"rl_{replay_id}"
        return "rl_" + hashlib.md5(str(record)[:256].encode()).hexdigest()[:16]


# ------------------------------------------------------------------
# Module-level helpers
# ------------------------------------------------------------------

def _is_ballchasing_json(record: dict) -> bool:
    """True if record looks like a Ballchasing API /replays/{id} response."""
    return "blue" in record and "orange" in record and "_hits" not in record


def _player_id(player: dict) -> str:
    """Stable player identifier from Ballchasing player object."""
    pid = player.get("id", {})
    platform = pid.get("platform", "unknown")
    uid = pid.get("id", player.get("name", "unknown"))
    return f"{platform}:{uid}"
